fix build error due to unused imports
src/App.vue(2,1): error TS6133: 'Main' is declared but its value is never read.
src/App.vue(3,1): error TS6133: 'Identity' is declared but its value is never read.
error Command failed with exit code 2.